export const snowflakeKeywords = [
  'QUALIFY', 'MATCH_RECOGNIZE', 'PIVOT', 'UNPIVOT', 'LATERAL', 'FLATTEN', 'CHANGES',
  'AT', 'BEFORE', 'WAREHOUSE', 'STAGE', 'STREAM', 'TASK', 'RESUME', 'SUSPEND',
  'CLONE', 'COPY', 'MERGE', 'OBJECT_CONSTRUCT', 'OBJECT_INSERT', 'ARRAY_CONSTRUCT',
  'IDENTIFIER', 'RESULT_SCAN', 'GRANT', 'REVOKE', 'OWNERSHIP', 'USAGE', 'OPERATE',
  'MONITOR', 'EXECUTE', 'CALLER', 'OWNER', 'RUNTIME_VERSION', 'RETURNS', 'LANGUAGE',
  'JAVASCRIPT', 'SQL', 'PYTHON', 'JAVA', 'SCALA', 'AGGREGATE', 'TABLE', 'VOLATILE',
  'IMMUTABLE'
];

export const snowflakeBuiltins = [
  'CONCAT', 'SUBSTRING', 'SUBSTR', 'SPLIT', 'SPLIT_PART', 'REGEXP_LIKE', 'REGEXP_REPLACE',
  'REGEXP_SUBSTR', 'REGEXP_INSTR', 'LIKE', 'ILIKE', 'RLIKE', 'LTRIM', 'RTRIM', 'LOWER',
  'UPPER', 'LENGTH', 'LEN', 'CHARINDEX', 'POSITION', 'REPLACE', 'TRANSLATE',
  'ABS', 'CEIL', 'FLOOR', 'ROUND', 'TRUNC', 'MOD', 'POW', 'POWER', 'SQRT', 'LOG', 'LN',
  'EXP', 'GREATEST', 'LEAST', 'SIGN',
  'CURRENT_TIMESTAMP', 'CURRENT_DATE', 'CURRENT_TIME', 'SYSDATE', 'DATEADD', 'DATEDIFF',
  'DATE_TRUNC', 'DATE_PART', 'TO_TIMESTAMP', 'TO_DATE', 'TO_TIME', 'EXTRACT', 'LAST_DAY',
  'MONTHNAME', 'DAYNAME',
  'COUNT', 'SUM', 'AVG', 'MIN', 'MAX', 'MEDIAN', 'STDDEV', 'VARIANCE', 'LISTAGG',
  'ARRAY_AGG', 'OBJECT_AGG', 'APPROX_COUNT_DISTINCT', 'PERCENTILE_CONT', 'PERCENTILE_DISC',
  'ROW_NUMBER', 'RANK', 'DENSE_RANK', 'NTILE', 'LAG', 'LEAD', 'FIRST_VALUE', 'LAST_VALUE',
  'NTH_VALUE', 'CUME_DIST', 'PERCENT_RANK', 'RATIO_TO_REPORT',
  'CAST', 'TRY_CAST', 'TO_NUMBER', 'TO_VARCHAR', 'TO_BOOLEAN', 'IFF', 'NVL', 'NVL2',
  'COALESCE', 'NULLIF', 'DECODE',
  'CURRENT_ROLE', 'CURRENT_WAREHOUSE', 'CURRENT_DATABASE', 'CURRENT_SCHEMA',
  'CURRENT_ACCOUNT', 'CURRENT_REGION', 'CURRENT_USER', 'CURRENT_SESSION',
  'SYSTEM$WAIT', 'SYSTEM$CANCEL_QUERY', 'HASH', 'MD5', 'SHA1', 'SHA2', 'UUID_STRING',
  'PARSE_JSON', 'TO_JSON', 'OBJECT_KEYS', 'GET_PATH'
];

export const snowflakeTypes = [
  'VARCHAR', 'STRING', 'TEXT', 'CHAR', 'NUMBER', 'DECIMAL', 'NUMERIC', 'INT', 'INTEGER',
  'BIGINT', 'SMALLINT', 'TINYINT', 'BYTEINT', 'FLOAT', 'FLOAT4', 'FLOAT8', 'DOUBLE',
  'REAL', 'BOOLEAN', 'DATE', 'DATETIME', 'TIME', 'TIMESTAMP', 'TIMESTAMP_LTZ',
  'TIMESTAMP_NTZ', 'TIMESTAMP_TZ', 'VARIANT', 'OBJECT', 'ARRAY', 'GEOGRAPHY',
  'GEOMETRY', 'BINARY', 'VARBINARY'
];
